2021-08-05 14:27:22,996 ERROR: Exception on /auth/login [GET] [in d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Term\python_learn\microblog\app\auth\routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\term\python_learn\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Term\python_learn\microblog\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\Term\python_learn\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "D:\Term\python_learn\microblog\app\templates\base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "d:\term\python_learn\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2021-08-05 14:27:35,357 ERROR: Exception on /auth/login [GET] [in d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py:1454]
Traceback (most recent call last):
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 2070, in wsgi_app
    response = self.full_dispatch_request()
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 1515, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 1513, in full_dispatch_request
    rv = self.dispatch_request()
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\app.py", line 1499, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**req.view_args)
  File "D:\Term\python_learn\microblog\app\auth\routes.py", line 28, in login
    return render_template('auth/login.html', title=_('Sign In'), form=form)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\templating.py", line 147, in render_template
    return _render(
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\templating.py", line 128, in _render
    rv = template.render(context)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\jinja2\environment.py", line 1304, in render
    self.environment.handle_exception()
  File "d:\term\python_learn\microblog\venv\lib\site-packages\jinja2\environment.py", line 925, in handle_exception
    raise rewrite_traceback_stack(source=source)
  File "D:\Term\python_learn\microblog\app\templates\auth\login.html", line 2, in top-level template code
    {% import 'bootstrap/wtf.html' as wtf %}
  File "D:\Term\python_learn\microblog\app\templates\base.html", line 1, in top-level template code
    {% extends 'bootstrap/base.html' %}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 1, in top-level template code
    {% block doc -%}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 4, in block 'doc'
    {%- block html %}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 20, in block 'html'
    {% block body -%}
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask_bootstrap\templates\bootstrap\base.html", line 21, in block 'body'
    {% block navbar %}
  File "D:\Term\python_learn\microblog\app\templates\base.html", line 17, in block 'navbar'
    <a class="navbar-brand" href="{{ url_for('index') }}">Microblog</a>
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\helpers.py", line 338, in url_for
    return appctx.app.handle_url_build_error(error, endpoint, values)
  File "d:\term\python_learn\microblog\venv\lib\site-packages\flask\helpers.py", line 325, in url_for
    rv = url_adapter.build(
  File "d:\term\python_learn\microblog\venv\lib\site-packages\werkzeug\routing.py", line 2305, in build
    raise BuildError(endpoint, values, method, self)
werkzeug.routing.BuildError: Could not build url for endpoint 'index'. Did you mean 'main.index' instead?
2021-08-05 14:35:00,077 INFO: Microblog startup [in D:\Term\python_learn\microblog\app\__init__.py:74]
